package Hackerrank;
/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

//Input Format
First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.

//Output Format
Print the required answer for each test case.


 */

import java.util.*;

public class Even_Fibonacci_numbers {

    public static void main(String[] args) {
        try (Scanner in = new Scanner(System.in)) {
            int t = in.nextInt();
            for(int a0 = 0; a0 < t; a0++){
                long n = in.nextLong();
                long sum = evenFibonacciSum(n);
                System.out.println(sum);
            }
        }
    }

    private static long evenFibonacciSum(long n){
        long sum = 0;
        long current = 2;
        long previous = 1;

        while (current <= n) {
            if (current % 2 == 0) {
                sum += current;
            }

            long next = current + previous;
            previous = current;
            current = next;
        }
        return sum;
    }
}
