/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

Answer :  5482660
 */


package Hackerrank;

import java.util.Iterator;
import java.util.Scanner;
import java.util.SortedSet;
import java.util.TreeSet;

public class Pentagon_nums {
    public static void main(String[] args) {
        /* Enter your code here. Read input from STDIN. Print output to STDOUT. Your class should be named Solution. */
        Scanner in = new Scanner(System.in);
        int n = in.nextInt();
        int k = in.nextInt();
        SortedSet<Long> res = new TreeSet<Long>();

        for(long i=k+1;i<=n;i++)
        {
            long pn = (long)(i*((3*i)-1)/2);
            long j = i-k;
            long pNMinusK = (long)(j*((3*j)-1)/2);
            if(isPentagonal(pn-pNMinusK) || isPentagonal(pn+pNMinusK))
                res.add(pn);
        }
        Iterator it = res.iterator();
        while (it.hasNext())
            System.out.println(String.valueOf(it.next()));
    }

    private static boolean isPentagonal(long number)
    {
        double penTest = (Math.sqrt(1 + 24 * number) + 1.0) / 6.0;
        return penTest == ((long)penTest);
    }
}
