/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Answer : 1533776805

 */

package Hackerrank;

import java.util.Scanner;

public class Triangle_pentagonal_hexagonal {
    public static void main(String[] args) {
        /* Enter your code here. Read input from STDIN. Print output to STDOUT. Your class should be named Solution. */
        Scanner in = new Scanner(System.in);
        long n = in.nextLong();
        int a = in.nextInt();
        int b = in.nextInt();
        int increment = 4;

        for(long i=1;i<n;i++)
        {
            if(a==3)
            {
                if(isTriangularNumber(i))
                    System.out.println(i);
                if(i==1) i+=3;
                else if(i>4)
                {
                    i+=increment+2;
                    increment+=3;
                }
            }
            else
            {
                if(isHexagonalNumber(i))
                    System.out.println(i);
                if(i==1) i+=3;
                else if(i>4)
                {
                    i+=increment+2;
                    increment+=3;
                }
            }
        }
    }

    public static boolean isTriangularNumber(long n)
    {
        double tTest = Math.sqrt(1 + 8*n);
        return tTest == ((long)tTest);
    }

    private static boolean isHexagonalNumber(long number)
    {
        double hexTest = (Math.sqrt(1 + 8*number) + 1.0) / 4.0;
        return hexTest == ((long)hexTest);
    }
}
